"""initial schema

Revision ID: 4ebabd87b3eb
Revises: 
Create Date: 2026-07-28 10:04:21.252684
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ebabd87b3eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealerships',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('company_number', sa.String(length=20), nullable=True),
    sa.Column('vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('postcode', sa.String(length=12), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_target_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_risk_reserve', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mandatory_min_risk_reserve', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_min_roi', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('default_vat_treatment', sa.String(length=20), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_acceptable_pessimistic_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allow_category_n', sa.Boolean(), nullable=False),
    sa.Column('allow_category_s', sa.Boolean(), nullable=False),
    sa.Column('risk_weights', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_houses',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('fee_calc_type', sa.String(length=30), nullable=False),
    sa.Column('default_transport_estimate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_houses_dealership_id'), 'auction_houses', ['dealership_id'], unique=False)
    op.create_table('users',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dealership_id'), 'users', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=12), nullable=True),
    sa.Column('vin', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('derivative', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('engine_size', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=40), nullable=True),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('previous_keepers', sa.Integer(), nullable=True),
    sa.Column('number_of_keys', sa.Integer(), nullable=True),
    sa.Column('euro_status', sa.String(length=10), nullable=True),
    sa.Column('ulez_compliant', sa.Boolean(), nullable=True),
    sa.Column('category_marker', sa.String(length=4), nullable=True),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_dealership_id'), 'vehicles', ['dealership_id'], unique=False)
    op.create_table('auction_fee_bands',
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('fixed_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('minimum_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maximum_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_applicable', sa.Boolean(), nullable=False),
    sa.Column('stated_inclusive', sa.Boolean(), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=True),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_fee_bands_auction_house_id'), 'auction_fee_bands', ['auction_house_id'], unique=False)
    op.create_table('auction_listings',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=20), nullable=True),
    sa.Column('auction_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guide_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cap_clean', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cap_average', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cap_below', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_retail', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starting_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reserve_status', sa.String(length=20), nullable=True),
    sa.Column('condition_grade', sa.Integer(), nullable=True),
    sa.Column('mechanical_report', sa.Text(), nullable=True),
    sa.Column('seller_declaration', sa.Text(), nullable=True),
    sa.Column('runner_status', sa.String(length=20), nullable=True),
    sa.Column('vat_status', sa.String(length=20), nullable=False),
    sa.Column('direct_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('listing_status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_listings_auction_house_id'), 'auction_listings', ['auction_house_id'], unique=False)
    op.create_index(op.f('ix_auction_listings_dealership_id'), 'auction_listings', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_auction_listings_vehicle_id'), 'auction_listings', ['vehicle_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_dealership_id'), 'audit_logs', ['dealership_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('vehicle_histories',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mot_expiry', sa.Date(), nullable=True),
    sa.Column('mot_pass_count', sa.Integer(), nullable=False),
    sa.Column('mot_fail_count', sa.Integer(), nullable=False),
    sa.Column('advisory_count', sa.Integer(), nullable=False),
    sa.Column('major_defect_count', sa.Integer(), nullable=False),
    sa.Column('dangerous_defect_count', sa.Integer(), nullable=False),
    sa.Column('repeated_failures', sa.Boolean(), nullable=False),
    sa.Column('outstanding_recall', sa.Boolean(), nullable=False),
    sa.Column('finance_marker', sa.Boolean(), nullable=False),
    sa.Column('stolen_marker', sa.Boolean(), nullable=False),
    sa.Column('write_off_marker', sa.Boolean(), nullable=False),
    sa.Column('mileage_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('plate_changes', sa.Integer(), nullable=False),
    sa.Column('keeper_changes', sa.Integer(), nullable=False),
    sa.Column('service_history_status', sa.String(length=20), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('last_service_mileage', sa.Integer(), nullable=True),
    sa.Column('history_provider', sa.String(length=40), nullable=False),
    sa.Column('data_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_histories_vehicle_id'), 'vehicle_histories', ['vehicle_id'], unique=True)
    op.create_table('appraisals',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('auction_listing_id', sa.Integer(), nullable=True),
    sa.Column('appraiser_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conservative_retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('optimistic_retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_negotiated_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pricing_confidence', sa.String(length=10), nullable=False),
    sa.Column('target_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_reserve', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desired_roi', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('estimated_days_to_sell', sa.Integer(), nullable=False),
    sa.Column('current_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('safe_max_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('absolute_max_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('break_even_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pessimistic_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('optimistic_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_roi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appraiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['auction_listing_id'], ['auction_listings.id'], ),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisals_appraiser_id'), 'appraisals', ['appraiser_id'], unique=False)
    op.create_index(op.f('ix_appraisals_auction_listing_id'), 'appraisals', ['auction_listing_id'], unique=False)
    op.create_index(op.f('ix_appraisals_dealership_id'), 'appraisals', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_appraisals_vehicle_id'), 'appraisals', ['vehicle_id'], unique=False)
    op.create_table('cost_items',
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maximum_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_treatment', sa.String(length=20), nullable=False),
    sa.Column('certainty', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_items_appraisal_id'), 'cost_items', ['appraisal_id'], unique=False)
    op.create_table('market_comparables',
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('listing_reference', sa.String(length=80), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('trim', sa.String(length=120), nullable=True),
    sa.Column('distance_miles', sa.Integer(), nullable=True),
    sa.Column('seller_type', sa.String(length=20), nullable=True),
    sa.Column('days_listed', sa.Integer(), nullable=True),
    sa.Column('price_change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('captured_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_comparables_appraisal_id'), 'market_comparables', ['appraisal_id'], unique=False)
    op.create_table('purchases',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('actual_hammer_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_auction_fees', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_transport_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('funding_source', sa.String(length=60), nullable=True),
    sa.Column('stock_number', sa.String(length=40), nullable=True),
    sa.Column('purchased_by_id', sa.Integer(), nullable=False),
    sa.Column('preparation_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.ForeignKeyConstraint(['purchased_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_appraisal_id'), 'purchases', ['appraisal_id'], unique=True)
    op.create_index(op.f('ix_purchases_dealership_id'), 'purchases', ['dealership_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('weighted_total', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=False),
    sa.Column('warning_flags', sa.JSON(), nullable=False),
    sa.Column('critical_flags', sa.JSON(), nullable=False),
    sa.Column('suggested_risk_reserve', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_appraisal_id'), 'risk_assessments', ['appraisal_id'], unique=True)
    op.create_table('preparation_costs',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_treatment', sa.String(length=20), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=True),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_costs_purchase_id'), 'preparation_costs', ['purchase_id'], unique=False)
    op.create_table('sales',
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('advertised_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('customer_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warranty_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advertising_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('finance_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('part_exchange_adjustment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_contribution', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('days_in_stock', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_dealership_id'), 'sales', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_sales_purchase_id'), 'sales', ['purchase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_purchase_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_dealership_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_preparation_costs_purchase_id'), table_name='preparation_costs')
    op.drop_table('preparation_costs')
    op.drop_index(op.f('ix_risk_assessments_appraisal_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_purchases_dealership_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_appraisal_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_market_comparables_appraisal_id'), table_name='market_comparables')
    op.drop_table('market_comparables')
    op.drop_index(op.f('ix_cost_items_appraisal_id'), table_name='cost_items')
    op.drop_table('cost_items')
    op.drop_index(op.f('ix_appraisals_vehicle_id'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_dealership_id'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_auction_listing_id'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_appraiser_id'), table_name='appraisals')
    op.drop_table('appraisals')
    op.drop_index(op.f('ix_vehicle_histories_vehicle_id'), table_name='vehicle_histories')
    op.drop_table('vehicle_histories')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_audit_logs_dealership_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_auction_listings_vehicle_id'), table_name='auction_listings')
    op.drop_index(op.f('ix_auction_listings_dealership_id'), table_name='auction_listings')
    op.drop_index(op.f('ix_auction_listings_auction_house_id'), table_name='auction_listings')
    op.drop_table('auction_listings')
    op.drop_index(op.f('ix_auction_fee_bands_auction_house_id'), table_name='auction_fee_bands')
    op.drop_table('auction_fee_bands')
    op.drop_index(op.f('ix_vehicles_dealership_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dealership_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_auction_houses_dealership_id'), table_name='auction_houses')
    op.drop_table('auction_houses')
    op.drop_table('dealerships')
    # ### end Alembic commands ###
