"""add listing image and spin urls

Revision ID: 8565c2dc5b5a
Revises: 4ebabd87b3eb
Create Date: 2026-07-28 11:56:06.682417
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8565c2dc5b5a'
down_revision: Union[str, None] = '4ebabd87b3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_listings', sa.Column(
        'image_urls', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('auction_listings', sa.Column(
        'spin_urls', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_listings', 'spin_urls')
    op.drop_column('auction_listings', 'image_urls')
    # ### end Alembic commands ###
