"""add auction house postcode

Revision ID: a790091bcfc8
Revises: 8565c2dc5b5a
Create Date: 2026-07-28 15:15:00.099830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a790091bcfc8'
down_revision: Union[str, None] = '8565c2dc5b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_houses', sa.Column('postcode', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_houses', 'postcode')
    # ### end Alembic commands ###
